
#include QMK_KEYBOARD_H


#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT(KC_LALT, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_BSPC, KC_ESC, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, KC_QUOT, KC_TAB, KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, KC_LGUI, KC_LCTL, KC_ENT, KC_LSFT, KC_SPC, MO(1), MO(2)),

[_LAYER1] = LAYOUT(KC_NO, KC_F9, KC_F10, KC_F11, KC_F12, KC_PSCR, KC_RBRC, KC_7, KC_8, KC_9, KC_MINS, KC_BSPC, KC_NO, KC_F5, KC_F6, KC_F7, KC_F8, KC_DEL, KC_LBRC, KC_4, KC_5, KC_6, KC_0, KC_EQL, KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_NO, KC_NUBS, KC_1, KC_2, KC_3, KC_NUHS, KC_GRV, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_TRNS, KC_NO),

[_LAYER2] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLD, KC_VOLU, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPRV, KC_MNXT, KC_MPLY, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS) 

};
